#+TITLE: Org language configuration
#+AUTHOR: Philip Hartout
#+EMAIL: <philip.hartout@protonmail.com>
#+DATE: Saturday November  5, 2022

* Sources

The configuration for this lanuage is stolen partly from [[https://zzamboni.org/post/beautifying-org-mode-in-emacs/][this website]] and [[https://config.daviwil.com/][David Wilson's config]].

* org-mode general appearance

** [[packa][Org-bullets]]

Show org-mode bullets as UTF-8 characters.

#+begin_src elisp
(use-package org-bullets
    :config
    (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+end_src

** General variables
*** Hide emphasis markers

#+begin_src elisp
(setq org-hide-emphasis-markers t)
#+end_src

*** [[https://orgmode.org/manual/Special-Symbols.html][Pretty entities]]

Turns on pretty entities by default. =org-toggle-pretty-entities= can turn them on or off in each buffer.

#+begin_src elisp
(setq org-pretty-entities t)
#+end_src

*** Unordered list font

Font lock substitutions for unordered lists.
#+begin_src elisp
(font-lock-add-keywords 'org-mode
                          '(("^ *\\([-]\\) "
                             (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

#+end_src

*** Visual-line-mode

Visual-line-mode enables the text of org documents to reflow.

#+begin_src elisp
(add-hook 'org-mode-hook 'visual-line-mode)
#+end_src

*** Custom faces for =palenight=.

Set faces for theme
#+begin_src elisp
(custom-theme-set-faces
   'user
   '(org-block ((t (:inherit fixed-pitch))))
   '(org-code ((t (:inherit (shadow fixed-pitch)))))
   '(org-document-info ((t (:foreground "dark orange"))))
   '(org-document-info-keyword ((t (:inherit (shadow fixed-pitch)))))
   '(org-indent ((t (:inherit (org-hide fixed-pitch)))))
   '(org-link ((t (:foreground "royal blue" :underline t))))
   '(org-meta-line ((t (:inherit (font-lock-comment-face fixed-pitch)))))
   '(org-property-value ((t (:inherit fixed-pitch))) t)
   '(org-special-keyword ((t (:inherit (font-lock-comment-face fixed-pitch)))))
   '(org-table ((t (:inherit fixed-pitch :foreground "#83a598"))))
   '(org-tag ((t (:inherit (shadow fixed-pitch) :weight bold :height 0.8))))
   '(org-verbatim ((t (:inherit (shadow fixed-pitch))))))
#+end_src

* Org mode behavior

** Indentation

#+begin_src elisp
(setq tab-width 2)
(setq org-src-preserve-indentation nil)
(setq org-edit-src-content-indentation 0)
#+end_src

** Org refiling targets

#+begin_src elisp
(setq org-refile-targets '(("~/Documents/Git/org/gtd.org" :maxlevel . 3)
                           ("~/Documents/Git/org/someday.org" :maxlevel . 3)
                           ("~/Documents/Git/org/today.org" :maxlevel . 3)))
#+end_src

** Code blocks
[[are][Code blocks]] embed code into org mode.
*** Structured templates

#+begin_src elisp

(setq org-structure-template-alist
      '(("a" . "export ascii\n")
        ("b" . "src bibtex")
        ("c" . "center\n")
        ("C" . "comment\n")
        ("e" . "src elisp\n")
        ("E" . "export")
        ("h" . "export html\n")
        ("l" . "export latex\n")
	("p" . "src python")
        ("q" . "quote\n")
        ("s" . "src")
        ("v" . "verse\n")))
#+end_src

*** org-tempo

Insert structured templates faster with =org-tempo=. See [[https://github.com/dangom/org-mode/blob/master/lisp/org-tempo.el][here]].

#+begin_src elisp
(with-eval-after-load 'org
  ;; This is needed as of Org 9.2
  (require 'org-tempo)

  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("py" . "src python")))
#+end_src

*** Code block execution
#+begin_src elisp
(with-eval-after-load 'org
  (org-babel-do-load-languages
   'org-babel-load-languages
      '((emacs-lisp . t)
	(python . t))))
#+end_src

From Paul, copies and executes the code block in the shell
#+begin_src elisp


(defun org-execute-code-in-shell  (&optional arg _info)
  "Copy current src block's contents and execute it in code shell buffer."
  (interactive "P")
  (let ((this-window (selected-window))
	(info (org-babel-get-src-block-info)))
    (org-babel-switch-to-session arg info)
    (end-of-buffer)
    (yank)
    (comint-send-input)
    (comint-send-input)
    (comint-send-input)
    (select-window this-window)))
#+end_src

Rebind keys to org-execute-code-in-shell

#+begin_src elisp
(org-defkey org-mode-map "\C-c\C-c" `org-execute-code-in-shell)
(org-defkey org-mode-map "\C-c\c" 'org-ctrl-c-ctrl-c)
#+end_src

** TODO keywords

See how org mode [[https://orgmode.org/manual/Workflow-states.html][manages keywords]].

#+begin_src elisp

(setq org-todo-keywords
      '((sequence "TODO" "IN-PROGRESS" "WAITING" "VERIFY" "DONE" "CANCELED"
                  "FIXME" "TEMP")))
(setq org-todo-keyword-faces
      '(("TODO" .  "orange") ("STARTED" . "yellow") ("TODO" . "red") ("DONE" . "green")
        ("CANCELED" . (:foreground "blue" :weight bold))))

#+end_src

** File path links

#+begin_src emacs-lisp
(setq org-link-file-path-type 'relative)
#+end_src
* Org-roam

See [[https://www.orgroam.com/][website]]. This setup is from the David Wilson tutorial.

#+begin_src elisp

(use-package org-roam
  :ensure t
  :init
  (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory "~/org-roam")
  (org-roam-completion-everywhere t)
  (org-roam-capture-templates
   '(("d" "default" plain
      "%?"
      :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
      :unnarrowed t))
   ("p" "project" plain "* Goals\n\n%?\n\n* Tasks\n\n** TODO Add initial tasks\n\n* Dates\n\n"
    :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+filetags: Project")
    :unnarrowed t))
  
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n i" . org-roam-node-insert)
	 ("C-c n c" . org-roam-capture)
         :map org-mode-map
         ("C-M-i" . completion-at-point)
	 :map org-roam-dailies-map
	 ("Y" . org-roam-dailies-capture-yesterday)
         ("T" . org-roam-dailies-capture-tomorrow))
  :bind-keymap
  ("C-c n d" . org-roam-dailies-map)
  :config
  (require 'org-roam-dailies) ;; Ensure the keymap is available
  (org-roam-db-autosync-mode))

#+end_src

* Provide config to =init.el=

#+begin_src elisp

(provide 'language-org)

#+end_src


