#+BIND: org-export-use-babel nil
#+TITLE: TITLE
#+AUTHOR: Philip Hartout
#+EMAIL: <philip.hartout@protonmail.com>
#+DATE: `(format-time-string "%A %B %e, %Y")`
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:[a4paper,12pt,twoside]
#+LaTeX_HEADER:\usepackage[final]{pdfpages}
#+LaTeX_HEADER:\usepackage{amsfonts, amssymb}            % Math symbols
#+LaTeX_HEADER:\usepackage[top=3cm, bottom=3cm, left=3cm, right=3cm]{geometry}
#+LATEX_HEADER_EXTRA:\hypersetup{colorlinks=false, linkcolor=black, citecolor=black, filecolor=black, urlcolor=black}
#+PROPERTY: header-args :exports both :session python_emacs_session :cache :results value 
#+PROPERTY: header-args :exports none :tangle "~/Documents/Git/phd_utils/bibliography/refs.bib"
#+OPTIONS: ^:nil
#+OPTIONS: toc:nil
#+STARTUP: latexpreview
#+LATEX_COMPILER: pdflatexorg-mode restarted

* Research Project Proposal Form
** Title
Keywords, precise

** Abstract
The relevance of the domain. SOTA has properties, however these come
with fundamental limitations. Limitations are addressed (be technical
here!) and yield the following improvement (dataset & metrics). Now
domain is extended.

Make sure experiments are fully reproducible: Github repo where each
experiment is a separate folder where the method is copied over. One
script to get results, one to produce the plot from the result. All
plots must have axis labels and error bars, no tables.

** What is the main idea of the paper? Give 1-2 sentences.
Change in point of view, new data... Include a technical description of the new part.

** What are the main competitors of your approach? Discuss metrics.
List and links to implementations.

If the new method is the only that does x and y simultaneously,
include comparison partners of x and y

** How do you measure success?
Performance measure, runtime, interpretability on datasets (external validation)

** Why is your project relevant?
It is the only method that can accomplish both. Both is relevant because...
It is the 'best' method for the task. Improving the method for the task is relevant because...
It is the only method that can do the new task. The task is relevant because...

    
